-
  name: for web server
  hosts: server
  become: yes
  tasks:
  - 
    name: Install apache httpd  (state=present is optional)
    ansible.builtin.apt:
      name: apache2
      state: present
  -
    name: service start apache
    service:
      name: apache2
      enabled: yes
      state: started
  - 
    name: Template a file to /etc/file.conf
    ansible.builtin.template:
      remote_src: /home/ubuntu/ansible/creative-studio
      dest: /var/www/html/
      owner: ubuntu
      group: wheel
      mode: '0644'

