- 
  name: this is our first play.
  hosts: server
  become: yes
  tasks: 
    - 
      name: 'installing'
      apt: name="{{ item }}" state=present
      with_items: 
        - apache2
      name: "create a dummy file on websever1"
      service: 
        name: apache2
        state: stopped