- 
  name: this is our first play.
  hosts: server
  vars: 
    age: 17
   tasks: 
  -
    name: 'creating file using variable'
    debug: 
      msg: "your nabalak"
      when: age > 18
  - 
    name: 'creating file using variable'
    debug:
     msg: "your balak" 
     when: age < 18