- 
  name: this is our first play.
  hosts: server
  vars: 
    age: 15
  tasks: 
    - 
      name: 'creating file using variable'
      command: touch /tmp/18.txt
      when: age == 18
    - 
      name: 'creating file using variable'
      command: touch /tmp/grater_then_18.txt
      when: age > 18
    - 
      name: 'creating file using variable'
      command: touch /tmp/less_then_10.txt
      when: age < 10
    - 
      name: 'creating file using variable'
      command: touch /tmp/between_10_and_18.txt
      when: age > 10 and age < 18