# copy_file.yml

- name: command moudle 
  hosts: server

  tasks:
    - name: command module 
      shell: sudo apt install apache2 -y
      tags:
        - simple_copy
      service: 
        name: apache2
        state: started 
    