- 
  name: this is our first play.
  hosts: server
  vars: 
    age: 15
  tasks: 
    - 
      name: 'creating file using variable'
      debug:
        msg= "you are baccha"
        when: age < 18
    - 
      name: 'creating file using variable'
      debug:
        msg= "you are balak"
        when: age > 18