-
  name: for web server
  hosts: server
  become: yes
  tasks:
-
  name: install web server
    ansible.builtin.package:
      name: apache2
      state: present
-
  name: service start apache
    service:
    name: apache2
    enabled: yes
    state: started
